Annex
abenaTenkorang/Hello-Microverse pull request #1
Opened 2022-10-24 20:56 UTC by abenaTenkorang

the main has only the Readme file available

2022-10-24 21:29 UTC, topeogunleye reviewed
Hi @abenaTenkorang, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

![Try-Again](https://user-images.githubusercontent.com/52934128/180646051-aed7efa6-6d15-4853-9962-73186e366f2c.gif)

> ## (Highlights) Good Points: 💪 
> * Followed Github flow :heavy_check_mark:
> * Professional README file. :heavy_check_mark:

## Required Changes ♻️
_Check the comments under the review._
- [x]  Next time, and for future commits, I kindly suggest that you please make use of imperative mood in the subject line for your commit messages.
:x: Bad Commit Messages :x:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/52934128/197633338-a5ab1266-16f9-4c4a-9053-2c23082046bd.png">

### ✔️ Good Commit Messages: ✔️
✔️  Add fix for dark mode toggle state
✔️  Update README file.
✔️  Add styles to h1.

- [x] I kindly suggest that you use a feature a your branch name e.g `feature/Hello`

- [ ] Please refer to this article: please read it and apply it in your work from now on: [Professional repo - basic rules](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md);

>- [x] Please kindly add a more descriptive PR title and description.
> See an example below:

![pull_request_desc](https://user-images.githubusercontent.com/52934128/177452738-0610c008-a53a-454e-8aac-635cb4ed812c.gif)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] Please kindly fix your merge conflicts
<img width="571" alt="image" src="https://user-images.githubusercontent.com/52934128/197633529-a509a1bb-93a4-4994-a527-8668dd6bc09b.png">

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-24 21:29 UTC, topeogunleye commented on .github/workflow/linters.yml
> +name: Linters
- [ ] I kindly suggest that you fix the spelling of workflow to `workflows` so that your linters  can run and then you'll get results like the image below on github:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/52934128/197632546-bcc53939-1715-4c4e-8d87-df96f953a0ba.png">

- [ ] I kindly suggest that you ensure your linters result should be green. AKA: Linter should report NO errors.

2022-10-24 21:35 UTC, topeogunleye requested changes

2022-10-24 21:35 UTC, topeogunleye commented on .gitignore
> +/test.md
- [ ] Great job adding `test.md` to the `.gitignore`  file, however, please also add the `node_modules` directory as stated by the project requirements.

2022-10-24 21:38 UTC, topeogunleye commented on .gitignore
> +/test.md
- [ ] Great job adding `test.md` to the `.gitignore`  file, however, please also add the `node_modules` directory as stated by the project requirements.

2022-10-25 07:42 UTC, closed without merging

2022-10-25 09:28 UTC, abenaTenkorang commented on .github/workflow/linters.yml
> +name: Linters
i am really finding it hard to fix the conflit,can I get any assistance @topeogunleye

2022-10-25 10:40 UTC, abenaTenkorang commented
- Please kindly fix your merge conflicts
 - Great job adding test.md to the .gitignore file, however, please also add the node_modules directory as stated by the project requirements.
 - The changes requested by the previous reviewer has been implemented.

2022-10-25 12:07 UTC, Qoosim reviewed
#  *Status: Approved* :tada:  :heavy_check_mark: 

Hi @abenaTenkorang, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

_**kindly check some optional comments I left under the review and work on them**_ :pray: 

## Highlights

-   No linter errors. :heavy_check_mark: 
-   Correct GitHub Flow. :heavy_check_mark: 
-   Fait README file. :heavy_check_mark:


![](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

- [OPTIONAL] There's no linters setup in your project and any project that has no linters setup wouldn't be reviewed. Because this is your first project, you're pardoned for that and must not repeat itself in your subsequent projects aside this. Kindly learn how to set up linters in your projects.

- [OPTIONAL] I would like to recommend that you should always try to give your pull request a descriptive titile and summary. A little like `Hello Microverse Project` would have been better to `Annex`. In the description section, you're expected to state what you've done in the project. Take the format below as an example

```
  In this pull request, I was able to:
  -   set up the linters
  -   create index file and add `h1` tag with `Hello Microverse` as content.
  -   create css file to style the content of the index file.
  -   create test.md file and add it to `.gitignore` file.
  -  etc.
```
- Kindly modify both the title and the summary section of your project and request for another review. 

- Look at the current status of your PR page.

### Your PR Title

![PR-title](https://user-images.githubusercontent.com/26597432/197767159-0eb40623-c8fe-4214-b1ff-b907d3aceb23.png)


### Your PR summary
- Your summary looks too messy and you don't need all the information you added. Kindly follow the example I gave you above to make your PR summary on your subsequent projects.

![PR-summary](https://user-images.githubusercontent.com/26597432/197767228-86fa5b08-2ef0-4582-a110-d8a2f30aaddf.png)

2022-10-25 12:07 UTC, Qoosim commented on index.html
> +</body>
- [OPTIONAL] I would recommend you to add a class name to your `h1` element and use the class name inside your css file to style the content of your `h1` element. It is marked optional because the previous reviewer did not mention it but it is highly recommend because is part of the requirements for this project.

2022-10-25 12:07 UTC, Qoosim commented on style.css
> +}
- [OPTIONAL] Kindly use the class name to style the content of the `h1` instead of using element selector. It is for the best practices.